#!/bin/sh

set -o nounset
set -o errexit

if test "$#" = 0; then
    printf '>>> Welcome to NixOS installation script!\n\n'
    printf '>>> To partition uefi:\n'
    printf '>>> # %s uefi [SWAP 8GiB by default]\n\n' "$(basename "$0")"
    printf '>>> To partition mbr:\n'
    printf '>>> # %s mbr [SWAP 2GiB by default]\n\n' "$(basename "$0")"
    printf '>>> To install:\n'
    printf '>>> # %s install\n\n' "$(basename "$0")"
    exit 1
fi

case "${1}" in
    uefi)
        parted /dev/sda -- mklabel gpt
        parted /dev/sda -- mkpart primary 512MiB "-${2:-8GB}"
        parted /dev/sda -- mkpart primary linux-swap "-${2:-8GB}" 100%
        parted /dev/sda -- mkpart ESP fat32 1MiB 512MiB
        parted /dev/sda -- set 3 boot on
        mkfs.ext4 -L nixos /dev/sda1
        mkswap -L swap /dev/sda2
        mkfs.fat -F 32 -n boot /dev/sda3
        mount /dev/disk/by-label/nixos /mnt
        mkdir -p /mnt/boot
        mount /dev/disk/by-label/boot /mnt/boot
        swapon /dev/sda2
        nixos-generate-config --root /mnt
        ;;
    mbr)
        parted /dev/sda -- mklabel msdos
        parted /dev/sda -- mkpart primary 1MiB "-${2:-2GB}"
        parted /dev/sda -- mkpart primary linux-swap "-${2:-2GB}" 100%
        mkfs.ext4 -L nixos /dev/sda1
        mkswap -L swap /dev/sda2
        mount /dev/disk/by-label/nixos /mnt
        swapon /dev/sda2
        nixos-generate-config --root /mnt
        ;;
    install)
        printf '>>> Configuring the environment\n'
        printf '>>> Mapping ctrl to caps\n'
        loadkeys ./ctrl2caps.map
        printf '>>> Installing emacs\n'
        nix-build emacs.nix

        printf '>>> Install configuration.nix:'
        mv /mnt/etc/nixos/configuration.nix /mnt/etc/nixos/orig_configuration.nix
        mv ./configuration.nix /mnt/etc/nixos/configuration.nix
        mv ./colors.nix /mnt/etc/nixos/colors.nix
        printf '>>> User password: '
        read user_password
        echo "\"$(mkpasswd -m sha-512 "${user_password}")\"" >/mnt/etc/nixos/secrets.nix

        chmod 400 /mnt/etc/nixos/secrets.nix
        ./result/bin/emacs /mnt/etc/nixos/configuration.nix /mnt/etc/nixos/orig_configuration.nix

        printf '>>> ALL SET! Now run:\n'
        printf '>>> # nixos-install\n'
        printf '>>> # reboot\n\n'
        printf '>>> Login\n\n'
        printf '>>> $ nix-shell -p git --run "git clone ''https://github.com/xFA25E/nixpkgs-config'' .config/nixpkgs"\n'
        printf '>>> $ cd .config/nixpkgs"\n'
        printf '>>> $ ./install\n\n'
        printf '>>> Enjoy! :)\n'
        ;;
    *)
        printf '>>> Select installation type! For more details:\n'
        printf '>>> # %s\n' "$(basename $0)"
        exit 1
esac
